version: '3.9'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-CU8-ubuntu-16.04
    user: '0:0'
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password!23
      - MSSQL_PID=Developer
      - MSSQL_TCP_PORT=1433
  mssqlscripts:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - mssql
    command: /bin/bash -c 'until /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P "Password!23" -Q "create database Keycloak"; do sleep 5; done'
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    depends_on:
      - mssql
      - mssqlscripts
    ports:
      - '8080:8080'
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=mssql
      - DB_USER=sa
      - DB_PASSWORD=Password!23
      - DB_ADDR=mssql
      - DB_DATABASE=Keycloak
